<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>BetterGI.RemoteLite.Agent</RootNamespace>
    <AssemblyName>BetterGI.RemoteLite.Agent</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>0.3.1</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BetterGI.RemoteLite.Core\BetterGI.RemoteLite.Core.csproj" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\genshin-character-ensemble.jpg" Link="assets\genshin-character-ensemble.jpg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
